! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Fri Aug 12 14:12:49 2016
! Working directory    : /misc/data9/chili/kpp-2.2.3/perl
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'MONX           ','DRYACET        ','DRYCH2O        ', &
     'DRYH2O2        ','DRYHNO3        ','DRYN2O5        ', &
     'DRYNO2         ','DRYO3          ','DRYPAN         ', &
     'DRYIPMN        ','DRYNPMN        ','DRYPMNN        ', &
     'DRYPPN         ','DRYR4N2        ','DRYMVK         ', &
     'DRYMACR        ','DRYHAC         ','DRYALD2        ', &
     'SO4            ','MSA            ','LISOPOH        ', &
     'LISOPNO3       ','LBRO2H         ','LBRO2N         ', &
     'LTRO2H         ','LTRO2N         ','LXRO2H         ', &
     'LXRO2N         ','LNRO2H         ','LNRO2N         ', &
     'NRO2           ','NAP            ','DRYHOBr        ', &
     'DRYHBr         ','DRYBrNO3       ','DRYBr2         ', &
     'PYAC           ','DRYISOPND      ','DRYISOPNB      ', &
     'DRYRIP         ','DRYIEPOX       ','DRYMACRN       ', &
     'DRYMVKN        ','DRYPROPNN      ','DRYHCOOH       ', &
     'DRYACTA        ','DRYLVOC        ','DRYGLYX        ', &
     'DRYMGLY        ','DRYGLYC        ','DRYISN1        ', &
     'INDIOL         ','ISN1OA         ','ISN1OG         ', &
     'LVOCOA         ','SOAGX          ','SOAIE          ', &
     'SOAMG          ','SOAME          ','DRYIMAE        ', &
     'ISOPOH         ','ISOPO3         ','ISOPNO3        ', &
     'RIO2NO         ','RIO2HO2        ','RIO2OTH        ', &
     'PSOA1          ','PSOA2          ','CO2            ', &
     'DRYDEP         ','LVOC           ','IMAE           ', &
     'TOLU           ','XYLE           ','CHBr3          ', &
     'CH2Br2         ','CH3Br          ','BENZ           ', &
     'DHDN           ','BrNO2          ','PMNN           ', &
     'PPN            ','BRO2           ','TRO2           ', &
     'N2O5           ','XRO2           ','IEPOX          ', &
     'ALK4           ','HNO2           ','MAP            ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'MPN            ','IMAO3          ','DMS            ', &
     'C3H8           ','ETP            ','HNO4           ', &
     'MP             ','RA3P           ','RB3P           ', &
     'HOBr           ','Br2            ','HBr            ', &
     'RP             ','PAN            ','C2H6           ', &
     'H2O2           ','BrNO3          ','PP             ', &
     'PRPN           ','ATOOH          ','R4P            ', &
     'HC187          ','RIP            ','VRP            ', &
     'IAP            ','MRP            ','MOBA           ', &
     'MAOP           ','DHMOB          ','NPMN           ', &
     'INPN           ','ISNP           ','ETHLN          ', &
     'MACRNO2        ','ROH            ','MOBAOO         ', &
     'DIBOO          ','IPMN           ','MVKOO          ', &
     'CH3CHOO        ','ACET           ','GAOO           ', &
     'ISNOHOO        ','MGLYOO         ','MVKN           ', &
     'BrO            ','ISOP           ','PRPE           ', &
     'ISNOOB         ','MGLOO          ','HNO3           ', &
     'ISOPNB         ','A3O2           ','IEPOXOO        ', &
     'CH2OO          ','GLYX           ','MACRN          ', &
     'PROPNN         ','MACROO         ','PO2            ', &
     'ISNOOA         ','MAOPO2         ','B3O2           ', &
     'MAN2           ','KO2            ','GLYC           ', &
     'ISOPND         ','HC5OO          ','VRO2           ', &
     'PRN1           ','ETO2           ','RCO3           ', &
     'ATO2           ','R4N1           ','ISN1           ', &
     'NMAO3          ','MGLY           ','MRO2           ', &
     'HC5            ','RIO2           ','CH2O           ', &
     'ISOPNBO2       ','ISOPNDO2       ','INO2           ', &
     'R4O2           ','HAC            ','ALD2           ', &
     'R4N2           ','MACR           ','MVK            ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(24) :: SPC_NAMES_2 = (/ &
     'SO2            ','RCHO           ','MCO3           ', &
     'OH             ','MO2            ','NO             ', &
     'O3             ','NO2            ','NO3            ', &
     'CO             ','HO2            ','MEK            ', &
     'Br             ','ACTA           ','CH4            ', &
     'EMISSION       ','EOH            ','H2             ', &
     'H2O            ','HCOOH          ','MOH            ', &
     'O2             ','RCOOH          ','DUMMY          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(204) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2 /)

  INTEGER, PARAMETER, DIMENSION(204) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, &
      13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, &
      25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, &
      37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, &
      49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, &
      61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, &
      73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, &
      85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, &
      97, 98, 99,100,101,102,103,104,105,106,107,108, &
     109,110,111,112,113,114,115,116,117,118,119,120, &
     121,122,123,124,125,126,127,128,129,130,131,132, &
     133,134,135,136,137,138,139,140,141,142,143,144, &
     145,146,147,148,149,150,151,152,153,154,155,156, &
     157,158,159,160,161,162,163,164,165,166,167,168, &
     169,170,171,172,173,174,175,176,177,178,179,180, &
     181,182,183,184,185,186,187,188,189,190,191,192, &
     193,194,195,196,197,198,199,200,201,202,203,204 /)

  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '       NO + O3 --> NO2 + O2                                                                         ', &
     '       OH + O3 --> HO2 + O2                                                                         ', &
     '      O3 + HO2 --> OH + 2 O2                                                                        ', &
     '      O3 + NO2 --> NO3 + O2                                                                         ', &
     '      MO2 + O3 --> CH2O + HO2 + 2 O2                                                                ', &
     '          2 OH --> O3 + H2O                                                                         ', &
     '          2 OH --> H2O2                                                                             ', &
     '      OH + HO2 --> H2O + O2                                                                         ', &
     '     H2O2 + OH --> HO2 + H2O                                                                        ', &
     '      NO + HO2 --> OH + NO2                                                                         ', &
     '         2 HO2 --> H2O2                                                                             ', &
     '       OH + H2 --> HO2 + H2O                                                                        ', &
     '       OH + CO --> CO2 + HO2                                                                        ', &
     '      OH + CH4 --> MO2 + H2O                                                                        ', &
     '      MO2 + NO --> CH2O + NO2 + HO2                                                                 ', &
     '     MO2 + HO2 --> MP + O2                                                                          ', &
     '         2 MO2 --> CH2O + MOH + O2                                                                  ', &
     '         2 MO2 --> 2 CH2O + 2 HO2                                                                   ', &
     '       MP + OH --> MO2 + H2O                                                                        ', &
     '       MP + OH --> CH2O + OH + H2O                                                                  ', &
     '    ATOOH + OH --> ATO2 + H2O                                                                       ', &
     '    ATOOH + OH --> MGLY + OH + H2O                                                                  ', &
     '     CH2O + OH --> CO + HO2 + H2O                                                                   ', &
     '      OH + NO2 --> HNO3                                                                             ', &
     '     HNO3 + OH --> NO3 + H2O                                                                        ', &
     '       OH + NO --> HNO2                                                                             ', &
     '     HNO2 + OH --> NO2 + H2O                                                                        ', &
     '     NO2 + HO2 --> HNO4                                                                             ', &
     '          HNO4 --> NO2 + HO2                                                                        ', &
     '     HNO4 + OH --> NO2 + H2O + O2                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '     NO3 + HO2 --> OH + NO2 + O2                                                                    ', &
     '      NO + NO3 --> 2 NO2                                                                            ', &
     '      OH + NO3 --> NO2 + HO2                                                                        ', &
     '     NO2 + NO3 --> N2O5                                                                             ', &
     '          N2O5 --> NO2 + NO3                                                                        ', &
     '    OH + HCOOH --> CO2 + HO2 + H2O                                                                  ', &
     '      OH + MOH --> CH2O + HO2                                                                       ', &
     '     NO2 + NO3 --> NO + NO2 + O2                                                                    ', &
     '    CH2O + NO3 --> HNO3 + CO + HO2                                                                  ', &
     '     ALD2 + OH --> 0.05 CH2O + 0.95 MCO3 + 0.05 CO + 0.05 HO2                                       ', &
     '    ALD2 + NO3 --> HNO3 + MCO3                                                                      ', &
     '    MCO3 + NO2 --> PAN                                                                              ', &
     '           PAN --> MCO3 + NO2                                                                       ', &
     '     MCO3 + NO --> CO2 + MO2 + NO2                                                                  ', &
     '     C2H6 + OH --> ETO2 + H2O                                                                       ', &
     '     ETO2 + NO --> ALD2 + NO2 + HO2                                                                 ', &
     '     C3H8 + OH --> B3O2                                                                             ', &
     '     C3H8 + OH --> A3O2                                                                             ', &
     '     A3O2 + NO --> RCHO + NO2 + HO2                                                                 ', &
     '      PO2 + NO --> CH2O + ALD2 + NO2 + HO2                                                          ', &
     '     ALK4 + OH --> R4O2                                                                             ', &
     '     R4O2 + NO --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 ... etc.               ', &
     '     R4O2 + NO --> R4N2                                                                             ', &
     '     R4N1 + NO --> 0.39 CH2O + 0.3 R4O2 + 0.75 ALD2 + 0.57 RCHO + 2 NO2 ... etc.                    ', &
     '     ATO2 + NO --> 0.96 CH2O + 0.04 R4N2 + 0.96 MCO3 + 0.96 NO2                                     ', &
     '      KO2 + NO --> 0.93 ALD2 + 0.07 R4N2 + 0.93 MCO3 + 0.93 NO2                                     ', &
     '     RIO2 + NO --> RIO2NO + 0.1 DIBOO + 0.047 ISOPNB + 0.023 ISOPND + 0.12 HC5 ... etc.             ', &
     '          RIO2 --> 0.25 GLYX + 0.5 GLYC + 0.25 MGLY + CH2O + 0.5 HAC + OH ... etc.                  ', &
     '     VRO2 + NO --> 0.12 MVKN + 0.53 GLYC + 0.35 MGLY + 0.35 CH2O + 0.53 MCO3 ... etc.               ', &
     '     MRO2 + NO --> 0.15 MACRN + 0.122 MGLY + 0.122 CH2O + 0.728 HAC + 0.85 NO2 ... etc.             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '          MRO2 --> HAC + OH + CO                                                                    ', &
     '     MAN2 + NO --> 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 OH + 1.5 NO2 ... etc.                     ', &
     '     B3O2 + NO --> ACET + NO2 + HO2                                                                 ', &
     '     INO2 + NO --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK ... etc.                ', &
     '    INO2 + NO3 --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK ... etc.                ', &
     '    ISN1 + NO3 --> 0.4 ISNOOB + 0.6 HNO3 + 0.6 ISNOOA                                               ', &
     '  ISNOOA + NO3 --> 0.04 ISN1OG + 0.96 R4N2 + NO2 + CO + HO2                                         ', &
     '   ISNOOA + NO --> 0.04 ISN1OG + 0.96 R4N2 + NO2 + CO + HO2                                         ', &
     '  ISNOOA + NO2 --> 0.04 ISN1OG + 0.96 IPMN                                                          ', &
     '  ISNOOA + HO2 --> 0.04 ISN1OG + 0.75 RP + 0.25 O3 + 0.96 NO2 + 0.25 RCOOH ... etc.                 ', &
     '  ISNOOB + NO3 --> 0.04 ISN1OG + GLYX + 0.96 R4N2 + 2 NO2                                           ', &
     '   ISNOOB + NO --> 0.04 ISN1OG + 0.94 GLYX + 0.9 R4N2 + 1.88 NO2                                    ', &
     '  ISNOOB + HO2 --> 0.04 ISN1OG + 0.96 INPN                                                          ', &
     '  ISNOOB + MO2 --> 0.04 ISN1OG + 0.7 GLYX + 0.75 CH2O + 0.66 R4N2 + 0.7 NO2 ... etc.                ', &
     '     ISN1 + O3 --> 0.7 GLYX + 0.75 CH2O + 0.3 R4N2 + 0.7 NO2 + 0.5 HO2 ... etc.                     ', &
     '     ISN1 + OH --> 0.655 ISNOHOO + 0.345 ISNOOA                                                     ', &
     '  ISNOHOO + NO --> 0.04 ISN1OG + 0.919 GLYX + 0.894 R4N2 + 0.934 HO2                                ', &
     ' ISNOHOO + HO2 --> 0.04 ISN1OG + 0.96 INPN                                                          ', &
     ' ISNOHOO + MO2 --> 0.04 ISN1OG + 0.7 GLYX + 0.75 CH2O + 0.66 R4N2 + 1.2 HO2 ... etc.                ', &
     '        2 INO2 --> 0.5 ISOPND + 1.2 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR ... etc.               ', &
     '     PRN1 + NO --> CH2O + ALD2 + 2 NO2                                                              ', &
     '    ALK4 + NO3 --> HNO3 + R4O2                                                                      ', &
     '     R4N2 + OH --> R4N1 + H2O                                                                       ', &
     '     OH + ACTA --> CO2 + MO2 + H2O                                                                  ', &
     '     RCHO + OH --> RCO3 + H2O                                                                       ', &
     '    RCO3 + NO2 --> PPN                                                                              ', &
     '           PPN --> RCO3 + NO2                                                                       ', &
     '   IMAO3 + NO2 --> IPMN                                                                             ', &
     '   NMAO3 + NO2 --> NPMN                                                                             ', &
     '          IPMN --> IMAO3 + NO2                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '          NPMN --> NMAO3 + NO2                                                                      ', &
     '     RCO3 + NO --> ETO2 + NO2                                                                       ', &
     '    NMAO3 + NO --> CO2 + 0.5 CH2O + 0.5 MCO3 + 0.5 MO2 + NO2 + 0.5 CO                               ', &
     '    RCHO + NO3 --> HNO3 + RCO3                                                                      ', &
     '     ACET + OH --> ATO2 + H2O                                                                       ', &
     '     ACET + OH --> ATO2 + H2O                                                                       ', &
     '    A3O2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.75 RCHO + HO2 + 0.25 MOH                                ', &
     '     PO2 + MO2 --> 0.25 ROH + 1.25 CH2O + 0.16 HAC + 0.5 ALD2 + 0.09 RCHO ... etc.                  ', &
     '    R4O2 + HO2 --> R4P                                                                              ', &
     '    R4N1 + HO2 --> R4N2                                                                             ', &
     '    ATO2 + HO2 --> 0.85 ATOOH + 0.15 CH2O + 0.15 MCO3 + 0.15 OH                                     ', &
     '     KO2 + HO2 --> 0.85 ATOOH + 0.15 ALD2 + 0.15 MCO3 + 0.15 OH                                     ', &
     '    RIO2 + HO2 --> RIO2HO2 + 0.937 RIP + 0.063 CH2O + 0.025 MACR + 0.038 MVK ... etc.               ', &
     '    VRO2 + HO2 --> 0.1 VRP + 0.578 GLYC + 0.102 MGLY + 0.102 CH2O + 0.033 RCHO ... etc.             ', &
     '    MRO2 + HO2 --> MRP                                                                              ', &
     '    MAN2 + HO2 --> 0.85 ISNP + 0.075 PROPNN + 0.075 MGLY + 0.075 CH2O + 0.15 OH ... etc.            ', &
     '    B3O2 + HO2 --> RB3P                                                                             ', &
     '    INO2 + HO2 --> INPN                                                                             ', &
     '    PRN1 + HO2 --> PRPN                                                                             ', &
     '      OH + MEK --> KO2 + H2O                                                                        ', &
     '    ETO2 + MO2 --> 0.75 CH2O + 0.75 ALD2 + HO2 + 0.25 EOH + 0.25 MOH                                ', &
     '     NO3 + MEK --> HNO3 + KO2                                                                       ', &
     '    R4O2 + MO2 --> 0.25 ROH + 0.16 ACET + 0.03 A3O2 + 0.09 B3O2 + 0.16 ETO2 ... etc.                ', &
     '    R4N1 + MO2 --> 0.25 ROH + 0.95 CH2O + 0.15 R4O2 + 0.38 ALD2 + 0.54 RCHO ... etc.                ', &
     '    ATO2 + MO2 --> 0.5 MGLY + 0.5 CH2O + 0.2 HAC + 0.3 MCO3 + 0.3 HO2 + 0.5 MOH ... etc.            ', &
     '     KO2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.5 ALD2 + 0.5 MCO3 + 0.5 HO2 ... etc.                    ', &
     '    RIO2 + MO2 --> RIO2OTH + 0.24 ROH + 0.3 HC5 + 1.22 CH2O + 0.18 MACR ... etc.                    ', &
     '        2 RIO2 --> 2 RIO2OTH + 0.09 DIBOO + 1.11 HC5 + 0.75 CH2O + 0.29 MACR ... etc.               ', &
     '   HC5OO + MO2 --> 0.25 ROH + 0.13 GLYC + 0.29 MGLY + 0.95 CH2O + 0.18 HAC ... etc.                 ', &
     '    VRO2 + MO2 --> 0.25 ROH + 0.36 GLYC + 0.14 MGLY + 0.89 CH2O + 0.36 MCO3 ... etc.                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    MRO2 + MO2 --> 0.15 ROH + 0.255 MGLY + 1.255 CH2O + 0.595 HAC + 0.595 CO ... etc.               ', &
     '    MAN2 + MO2 --> 0.375 PROPNN + 0.375 MGLY + 0.625 CH2O + 0.25 R4N2 + 0.375 NO2 ... etc.          ', &
     '    B3O2 + MO2 --> 0.25 ROH + 0.75 ACET + 0.75 CH2O + HO2 + 0.25 MOH                                ', &
     '    INO2 + MO2 --> 0.25 ISOPND + 0.6 ISN1 + 0.115 HC5 + 0.785 CH2O + 0.018 MACR ... etc.            ', &
     '    PRN1 + MO2 --> 0.25 ROH + 1.25 CH2O + 0.5 ALD2 + 0.25 RCHO + NO2 + 0.5 HO2 ... etc.             ', &
     '      OH + EOH --> ALD2 + HO2                                                                       ', &
     '      ROH + OH --> RCHO + HO2                                                                       ', &
     '        2 ETO2 --> 2 ALD2 + 2 HO2                                                                   ', &
     '        2 ETO2 --> ALD2 + EOH                                                                       ', &
     '    ETO2 + HO2 --> ETP                                                                              ', &
     '    A3O2 + HO2 --> RA3P                                                                             ', &
     '     PO2 + HO2 --> PP                                                                               ', &
     '    MCO3 + HO2 --> 0.41 MAP + 0.44 OH + 0.44 MO2 + 0.15 O3 + 0.15 ACTA ... etc.                     ', &
     '    RCO3 + HO2 --> 0.41 RP + 0.44 ETO2 + 0.44 OH + 0.15 O3 + 0.15 RCOOH ... etc.                    ', &
     '   NMAO3 + HO2 --> 0.41 MAOP + 0.59 CH2O + 0.44 OH + 0.39 MO2 + 0.15 O3 ... etc.                    ', &
     '     PRPE + OH --> PO2                                                                              ', &
     '     PRPE + O3 --> 0.12 CH3CHOO + 0.12 CH2OO + 0.5 CH2O + 0.5 ALD2 + 0.36 OH ... etc.               ', &
     '     NPMN + OH --> HAC + NO2 + CO                                                                   ', &
     '     IPMN + OH --> 0.781 IMAE + 0.19 PAN + 0.19 CH2O + 0.03 HAC + 0.81 NO3 ... etc.                 ', &
     '     NPMN + O3 --> 0.6 CH2O + NO2 + HO2                                                             ', &
     '     IMAE + OH --> OH                                                                               ', &
     '     GLYC + OH --> 0.361 CO2 + 0.134 GLYX + 0.732 CH2O + 0.227 OH + 0.505 CO ... etc.               ', &
     '     GLYC + OH --> OH + CO + HCOOH                                                                  ', &
     '    PRPE + NO3 --> PRN1                                                                             ', &
     '     GLYX + OH --> 2 CO + HO2                                                                       ', &
     '     MGLY + OH --> MCO3 + CO                                                                        ', &
     '    GLYX + NO3 --> HNO3 + 2 CO + HO2                                                                ', &
     '    MGLY + NO3 --> HNO3 + MCO3 + CO                                                                 ', &
     '     ISOP + OH --> LISOPOH + ISOPOH + RIO2                                                          ', &
     '      MVK + OH --> VRO2                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '     MACR + OH --> 0.53 IMAO3 + 0.47 MRO2                                                           ', &
     '      HAC + OH --> MGLY + HO2                                                                       ', &
     '      HAC + OH --> 0.5 CO2 + OH + 0.5 MO2 + 0.5 CO + 0.5 ACTA + 0.5 HCOOH ... etc.                  ', &
     '   A3O2 + MCO3 --> RCHO + MO2 + HO2                                                                 ', &
     '    PO2 + MCO3 --> CH2O + ALD2 + MO2 + HO2                                                          ', &
     '   A3O2 + MCO3 --> RCHO + ACTA                                                                      ', &
     '    PO2 + MCO3 --> 0.65 HAC + 0.35 RCHO + ACTA                                                      ', &
     '     ISOP + O3 --> ISOPO3 + 0.044 MVKOO + 0.102 PRPE + 0.11 CH2OO + 0.044 MACROO ... etc.           ', &
     '      MVK + O3 --> 0.12 MGLOO + 0.12 CH2OO + 0.5 MGLY + 0.6 CH2O + 0.1 ALD2 ... etc.                ', &
     '     MACR + O3 --> 0.022 MGLYOO + 0.326 CH2OO + 0.88 MGLY + 0.12 CH2O + 0.098 MCO3 ... etc.         ', &
     '    ISOP + NO3 --> LISOPNO3 + ISOPNO3 + INO2                                                        ', &
     '    MACR + NO3 --> MAN2                                                                             ', &
     '    MACR + NO3 --> 0.5 IMAO3 + 0.5 MAOP + 0.5 HNO3 + 0.5 MRO2 + 0.5 CO ... etc.                     ', &
     '    RCO3 + MO2 --> ETO2 + CH2O + HO2                                                                ', &
     '   NMAO3 + MO2 --> 2 CH2O + MCO3 + HO2                                                              ', &
     '    RCO3 + MO2 --> CH2O + RCOOH                                                                     ', &
     '   NMAO3 + MO2 --> CH2O + RCOOH                                                                     ', &
     '     INPN + OH --> OH + NO2 + MEK                                                                   ', &
     '     INPN + OH --> 0.36 INO2 + 0.64 R4N2 + 0.64 OH                                                  ', &
     '     PRPN + OH --> 0.791 PROPNN + 0.209 PRN1 + 0.791 OH                                             ', &
     '      ETP + OH --> 0.36 ETO2 + 0.64 ALD2 + 0.64 OH                                                  ', &
     '     RA3P + OH --> 0.36 A3O2 + 0.64 RCHO + 0.64 OH                                                  ', &
     '     RB3P + OH --> 0.791 ACET + 0.209 B3O2 + 0.791 OH                                               ', &
     '      R4P + OH --> 0.209 R4O2 + 0.791 RCHO + 0.791 OH                                               ', &
     '       RP + OH --> RCO3                                                                             ', &
     '       PP + OH --> 0.209 PO2 + 0.791 HAC + 0.791 OH                                                 ', &
     '      RIP + OH --> 0.005 LVOC + 0.598 HC5 + 0.387 RIO2 + 0.598 OH                                   ', &
     '      RIP + OH --> 0.005 LVOC + 0.75 IEPOX + 0.985 OH                                               ', &
     '     LVOC + OH --> OH                                                                               ', &
     '    IEPOX + OH --> IEPOXOO                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     ' IEPOXOO + HO2 --> 1.1 CO2 + 0.44 HC187 + 0.085 GLYX + 0.025 GLYC + 0.085 MGLY ... etc.             ', &
     '  IEPOXOO + NO --> 0.8 CO2 + 0.473 HC187 + 0.088 GLYX + 0.088 GLYC + 0.088 MGLY ... etc.            ', &
     '    HC187 + OH --> 0.5 MGLY + CH2O + 0.5 MCO3 + 0.5 CO + 0.5 HO2                                    ', &
     '      IAP + OH --> 0.654 DHMOB + 0.346 HC5OO + 0.654 OH                                             ', &
     '      VRP + OH --> 0.209 VRO2 + 0.791 OH + 0.791 MEK                                                ', &
     '      MRP + OH --> MRO2                                                                             ', &
     '      MRP + OH --> CO2 + HAC + OH                                                                   ', &
     '     MAOP + OH --> NMAO3                                                                            ', &
     '     MAOP + OH --> MAOPO2                                                                           ', &
     ' MAOPO2 + MCO3 --> 2 CO2 + HAC + OH + MO2                                                           ', &
     ' MAOPO2 + MCO3 --> MEK + ACTA                                                                       ', &
     '  MAOPO2 + MO2 --> 0.7 CO2 + 0.3 ROH + CH2O + 0.7 HAC + 0.7 OH + 0.7 HO2 ... etc.                   ', &
     '      2 MAOPO2 --> 2 CO2 + 2 HAC + 2 OH                                                             ', &
     '  MAOPO2 + HO2 --> CO2 + HAC + 2 OH                                                                 ', &
     '   MAOPO2 + NO --> CO2 + HAC + OH + NO2                                                             ', &
     '   MAOPO2 + NO --> HNO3                                                                             ', &
     '      MAP + OH --> MCO3                                                                             ', &
     '    C2H6 + NO3 --> HNO3 + ETO2                                                                      ', &
     '      HC5 + O3 --> 0.055 GAOO + 0.055 MGLYOO + 0.5 GLYC + 0.5 MGLY + 0.445 CH2O ... etc.            ', &
     '        2 MCO3 --> 2 MO2                                                                            ', &
     '    MCO3 + MO2 --> CH2O + MO2 + HO2                                                                 ', &
     '    MCO3 + MO2 --> CH2O + ACTA                                                                      ', &
     '   R4O2 + MCO3 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 ... etc.               ', &
     '   ATO2 + MCO3 --> CH2O + MCO3 + MO2                                                                ', &
     '    KO2 + MCO3 --> ALD2 + MCO3 + MO2                                                                ', &
     '   RIO2 + MCO3 --> RIO2OTH + CO2 + 0.113 DIBOO + 0.14 HC5 + 0.747 CH2O ... etc.                     ', &
     '  HC5OO + MCO3 --> 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY ... etc.           ', &
     '   VRO2 + MCO3 --> 0.6 GLYC + 0.4 MGLY + 0.4 CH2O + 0.6 MCO3 + MO2 + 0.4 HO2 ... etc.               ', &
     '   MRO2 + MCO3 --> 0.143 MGLY + 0.143 CH2O + 0.857 HAC + MO2 + 0.857 CO ... etc.                    ', &
     '   B3O2 + MCO3 --> ACET + MO2 + HO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '   R4N1 + MCO3 --> 0.39 CH2O + 0.3 R4O2 + 0.75 ALD2 + 0.57 RCHO + MO2 + NO2 ... etc.                ', &
     '   MAN2 + MCO3 --> CO2 + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + MO2 + 0.5 NO2 ... etc.                  ', &
     '   INO2 + MCO3 --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK ... etc.                ', &
     '   PRN1 + MCO3 --> CH2O + ALD2 + MO2 + NO2                                                          ', &
     '   R4O2 + MCO3 --> MEK + ACTA                                                                       ', &
     '   ATO2 + MCO3 --> MEK + ACTA                                                                       ', &
     '    KO2 + MCO3 --> MEK + ACTA                                                                       ', &
     '   RIO2 + MCO3 --> RIO2OTH + MEK + ACTA                                                             ', &
     '  HC5OO + MCO3 --> MEK + ACTA                                                                       ', &
     '   VRO2 + MCO3 --> MEK + ACTA                                                                       ', &
     '   MRO2 + MCO3 --> MEK + ACTA                                                                       ', &
     '   R4N1 + MCO3 --> RCHO + NO2 + ACTA                                                                ', &
     '   MAN2 + MCO3 --> RCHO + NO2 + ACTA                                                                ', &
     '   INO2 + MCO3 --> RCHO + NO2 + ACTA                                                                ', &
     '   PRN1 + MCO3 --> RCHO + NO2 + ACTA                                                                ', &
     '   B3O2 + MCO3 --> ACET + ACTA                                                                      ', &
     '   ETO2 + MCO3 --> ALD2 + MO2 + HO2                                                                 ', &
     '   ETO2 + MCO3 --> ALD2 + ACTA                                                                      ', &
     '   RCO3 + MCO3 --> ETO2 + MO2                                                                       ', &
     '  NMAO3 + MCO3 --> CH2O + MCO3 + MO2                                                                ', &
     '         2 NO3 --> 2 NO2 + O2                                                                       ', &
     '     MO2 + NO2 --> MPN                                                                              ', &
     '           MPN --> MO2 + NO2                                                                        ', &
     '      EMISSION --> NO                                                                               ', &
     '      EMISSION --> NO2                                                                              ', &
     '      EMISSION --> CO                                                                               ', &
     '      EMISSION --> ALK4                                                                             ', &
     '      EMISSION --> ISOP                                                                             ', &
     '      EMISSION --> ACET                                                                             ', &
     '      EMISSION --> PRPE                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '      EMISSION --> C3H8                                                                             ', &
     '      EMISSION --> C2H6                                                                             ', &
     '      EMISSION --> MEK                                                                              ', &
     '      EMISSION --> ALD2                                                                             ', &
     '      EMISSION --> CH2O                                                                             ', &
     '      EMISSION --> O3                                                                               ', &
     '      EMISSION --> HNO3                                                                             ', &
     '      EMISSION --> CHBr3                                                                            ', &
     '      EMISSION --> CH2Br2                                                                           ', &
     '      EMISSION --> Br2                                                                              ', &
     '      EMISSION --> BENZ                                                                             ', &
     '      EMISSION --> TOLU                                                                             ', &
     '      EMISSION --> XYLE                                                                             ', &
     '      EMISSION --> NAP                                                                              ', &
     '      EMISSION --> MONX                                                                             ', &
     '      EMISSION --> GLYX                                                                             ', &
     '      EMISSION --> MGLY                                                                             ', &
     '          ACET --> DRYACET + DRYDEP                                                                 ', &
     '           NO2 --> DRYNO2 + DRYDEP                                                                  ', &
     '          PMNN --> DRYPMNN + DRYDEP                                                                 ', &
     '            O3 --> DRYO3 + DRYDEP                                                                   ', &
     '           PAN --> DRYPAN + DRYDEP                                                                  ', &
     '          HNO3 --> DRYHNO3 + DRYDEP                                                                 ', &
     '          CH2O --> DRYCH2O + DRYDEP                                                                 ', &
     '          N2O5 --> DRYN2O5 + DRYDEP                                                                 ', &
     '          H2O2 --> DRYH2O2 + DRYDEP                                                                 ', &
     '          IPMN --> DRYIPMN + DRYDEP                                                                 ', &
     '          NPMN --> DRYNPMN + DRYDEP                                                                 ', &
     '           PPN --> DRYPPN + DRYDEP                                                                  ', &
     '          R4N2 --> DRYR4N2 + DRYDEP                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '           MVK --> DRYMVK + DRYDEP                                                                  ', &
     '          MACR --> DRYMACR + DRYDEP                                                                 ', &
     '           HAC --> DRYHAC + DRYDEP                                                                  ', &
     '          ALD2 --> DRYALD2 + DRYDEP                                                                 ', &
     '         IEPOX --> DRYIEPOX + DRYDEP                                                                ', &
     '           RIP --> DRYRIP + DRYDEP                                                                  ', &
     '        ISOPND --> DRYISOPND + DRYDEP                                                               ', &
     '        ISOPNB --> DRYISOPNB + DRYDEP                                                               ', &
     '          GLYX --> DRYGLYX + DRYDEP                                                                 ', &
     '          MGLY --> DRYMGLY + DRYDEP                                                                 ', &
     '          GLYC --> DRYGLYC + DRYDEP                                                                 ', &
     '          ISN1 --> DRYISN1 + DRYDEP                                                                 ', &
     '          LVOC --> DRYLVOC + DRYDEP                                                                 ', &
     '   ISOPNB + O3 --> 0.36 CO2 + 0.21 MVKN + 0.41 HNO3 + 0.12 CH2OO + 0.32 MACRN ... etc.              ', &
     '   ISOPND + O3 --> 0.63 CO2 + 0.26 ETHLN + 0.3 HNO3 + 0.09 CH2OO + 0.06 GLYX ... etc.               ', &
     '    CH2OO + NO --> CH2O + NO2                                                                       ', &
     '   CH2OO + NO2 --> CH2O + NO3                                                                       ', &
     '   CH2OO + SO2 --> SO4 + CH2O                                                                       ', &
     '         CH2OO --> HCOOH                                                                            ', &
     '    MVKOO + CO --> MVK                                                                              ', &
     '    MVKOO + NO --> MVK + NO2                                                                        ', &
     '   MVKOO + NO2 --> MVK + NO3                                                                        ', &
     '   MVKOO + SO2 --> SO4 + MVK                                                                        ', &
     '         MVKOO --> H2O2 + MVK                                                                       ', &
     '   MACROO + CO --> MACR                                                                             ', &
     '   MACROO + NO --> MACR + NO2                                                                       ', &
     '  MACROO + NO2 --> MACR + NO3                                                                       ', &
     '  MACROO + SO2 --> SO4 + MACR                                                                       ', &
     '        MACROO --> MRP                                                                              ', &
     '        MACROO --> H2O2 + MACR                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '   MGLYOO + CO --> MGLY                                                                             ', &
     '   MGLYOO + NO --> MGLY + NO2                                                                       ', &
     '  MGLYOO + NO2 --> MGLY + NO3                                                                       ', &
     '  MGLYOO + SO2 --> SO4 + MGLY                                                                       ', &
     '        MGLYOO --> H2O2 + MGLY                                                                      ', &
     '    MGLOO + CO --> MGLY                                                                             ', &
     '    MGLOO + NO --> MGLY + NO2                                                                       ', &
     '   MGLOO + NO2 --> MGLY + NO3                                                                       ', &
     '   MGLOO + SO2 --> SO4 + MGLY                                                                       ', &
     '         MGLOO --> MCO3 + MO2                                                                       ', &
     '         MGLOO --> H2O2 + MGLY                                                                      ', &
     '        PROPNN --> DRYPROPNN + DRYDEP                                                               ', &
     '         MACRN --> DRYMACRN + DRYDEP                                                                ', &
     '          MVKN --> DRYMVKN + DRYDEP                                                                 ', &
     '         HCOOH --> DRYHCOOH + DRYDEP                                                                ', &
     '          ACTA --> DRYACTA + DRYDEP                                                                 ', &
     '          IMAE --> DRYIMAE + DRYDEP                                                                 ', &
     '           HO2 --> DUMMY                                                                            ', &
     '           NO2 --> 0.5 HNO2 + 0.5 HNO3                                                              ', &
     '           NO3 --> HNO3                                                                             ', &
     '          N2O5 --> 2 HNO3                                                                           ', &
     '          GLYX --> SOAGX                                                                            ', &
     '          MGLY --> SOAMG                                                                            ', &
     '         IEPOX --> SOAIE                                                                            ', &
     '          IMAE --> SOAME                                                                            ', &
     '          LVOC --> LVOCOA                                                                           ', &
     '        ISOPND --> INDIOL + PSOA1 + NO3                                                             ', &
     '        ISOPNB --> INDIOL + PSOA1 + NO3                                                             ', &
     '         MACRN --> INDIOL + NO3                                                                     ', &
     '          MVKN --> INDIOL + NO3                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '        PROPNN --> INDIOL + NO3                                                                     ', &
     '          R4N2 --> INDIOL + NO3                                                                     ', &
     '         ETHLN --> INDIOL + NO3                                                                     ', &
     '        ISN1OG --> ISN1OA                                                                           ', &
     '          DHDN --> INDIOL + PSOA2 + 2 NO3                                                           ', &
     '      DMS + OH --> CH2O + SO2 + MO2                                                                 ', &
     '      DMS + OH --> 0.25 MSA + 0.75 SO2 + MO2                                                        ', &
     '     DMS + NO3 --> HNO3 + CH2O + SO2 + MO2                                                          ', &
     '      SO2 + OH --> SO4 + HO2                                                                        ', &
     '       O3 + Br --> BrO + O2                                                                         ', &
     '     BrO + HO2 --> HOBr + O2                                                                        ', &
     '      HO2 + Br --> HBr + O2                                                                         ', &
     '      HBr + OH --> Br + H2O                                                                         ', &
     '         2 BrO --> 2 Br + O2                                                                        ', &
     '         2 BrO --> Br2 + O2                                                                         ', &
     '      BrO + NO --> NO2 + Br                                                                         ', &
     '    BrNO3 + Br --> Br2 + NO3                                                                        ', &
     '      Br2 + OH --> HOBr + Br                                                                        ', &
     '      BrO + OH --> HO2 + Br                                                                         ', &
     '      NO3 + Br --> BrO + NO2                                                                        ', &
     '     CH2O + Br --> HBr + CO + HO2                                                                   ', &
     '     ALD2 + Br --> HBr + MCO3 + CO                                                                  ', &
     '     ACET + Br --> HBr + ATO2 + CO                                                                  ', &
     '     C2H6 + Br --> HBr + ETO2 + CO                                                                  ', &
     '     C3H8 + Br --> HBr + A3O2 + CO                                                                  ', &
     '      NO2 + Br --> BrNO2                                                                            ', &
     '     BrO + NO2 --> BrNO3                                                                            ', &
     '    CHBr3 + OH --> 3 Br                                                                             ', &
     '   CH2Br2 + OH --> 2 Br                                                                             ', &
     '    CH3Br + OH --> Br                                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '         BrNO3 --> HOBr + HNO3                                                                      ', &
     '          HOBr --> 0.5 Br2 + H2O                                                                    ', &
     '           HBr --> 0.5 Br2                                                                          ', &
     '          HOBr --> 0.5 Br2 + H2O                                                                    ', &
     '           HBr --> 0.5 Br2                                                                          ', &
     '          HOBr --> DRYHOBr + DRYDEP                                                                 ', &
     '           HBr --> DRYHBr + DRYDEP                                                                  ', &
     '         BrNO3 --> DRYBrNO3 + DRYDEP                                                                ', &
     '           Br2 --> DRYBr2 + DRYDEP                                                                  ', &
     '      HC5 + OH --> HC5OO                                                                            ', &
     '    HC5OO + NO --> 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY ... etc.           ', &
     '    HC5OO + NO --> HNO3                                                                             ', &
     '   HC5OO + HO2 --> 0.1 IAP + 0.9 GLYC + 0.9 MGLY + 0.9 OH + 0.9 HO2                                 ', &
     '   ISOPND + OH --> 0.1 IEPOX + 0.9 ISOPNDO2 + 0.1 NO2                                               ', &
     '   ISOPNB + OH --> 0.1 IEPOX + 0.9 ISOPNBO2 + 0.1 NO2                                               ', &
     ' ISOPNDO2 + NO --> 0.27 DHDN + 0.21 ETHLN + 0.075 MVKN + 0.019 MACRN + 0.3 PROPNN ... etc.          ', &
     'ISOPNDO2 + HO2 --> 0.5 ISNP + 0.2 ETHLN + 0.06 MVKN + 0.01 MACRN + 0.23 PROPNN ... etc.             ', &
     ' ISOPNBO2 + NO --> 0.21 DHDN + 0.26 MVKN + 0.44 MACRN + 0.09 GLYC + 0.69 CH2O ... etc.              ', &
     'ISOPNBO2 + HO2 --> 0.5 ISNP + 0.16 MVKN + 0.28 MACRN + 0.06 GLYC + 0.44 CH2O ... etc.               ', &
     '     ISNP + OH --> 0.612 R4N1 + 0.193 ISOPNBO2 + 0.193 ISOPNDO2 + 0.612 OH ... etc.                 ', &
     '     MVKN + OH --> 0.35 PYAC + 0.65 MGLY + 0.35 CH2O + NO3 + 0.65 HCOOH ... etc.                    ', &
     '    MACRN + OH --> MACRNO2                                                                          ', &
     '  MACRNO2 + NO --> 0.93 CO2 + 0.07 MGLY + 0.08 CH2O + 0.85 HAC + 1.85 NO2 ... etc.                  ', &
     ' MACRNO2 + HO2 --> 0.93 CO2 + 0.07 MGLY + 0.08 CH2O + 0.85 HAC + OH + 0.85 NO2 ... etc.             ', &
     ' MACRNO2 + NO2 --> PMNN                                                                             ', &
     '          PMNN --> MACRNO2 + NO2                                                                    ', &
     '    DHMOB + OH --> 0.5 HAC + 1.5 CO + HO2 + 0.5 MEK                                                 ', &
     '    DIBOO + NO --> 0.48 GLYX + 0.52 GLYC + 0.52 MGLY + 0.48 HAC + NO2 + HO2 ... etc.                ', &
     '    DIBOO + NO --> HNO3                                                                             ', &
     '   DIBOO + HO2 --> 0.85 R4P + 0.072 GLYX + 0.078 GLYC + 0.078 MGLY + 0.072 HAC ... etc.             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '     MOBA + OH --> MOBAOO                                                                           ', &
     '   MOBAOO + NO --> CO2 + RCHO + NO2 + HO2                                                           ', &
     '   MOBAOO + NO --> HNO3                                                                             ', &
     '  MOBAOO + HO2 --> 0.5 CO2 + 0.5 R4P + 0.5 RCHO + 0.5 OH + 0.5 HO2                                  ', &
     '     MOBA + O3 --> CO2 + OH + HO2 + MEK                                                             ', &
     '    ETHLN + OH --> CO2 + CH2O + NO2                                                                 ', &
     '   PROPNN + OH --> MGLY + NO2                                                                       ', &
     '    CH2OO + NO --> CH2O + NO2                                                                       ', &
     '   CH2OO + NO2 --> CH2O + NO3                                                                       ', &
     '   CH2OO + SO2 --> SO4 + CH2O                                                                       ', &
     '         CH2OO --> H2O2 + CH2O                                                                      ', &
     '         CH2OO --> HCOOH                                                                            ', &
     '   MACROO + CO --> MACR                                                                             ', &
     '   MACROO + NO --> MACR + NO2                                                                       ', &
     '  MACROO + NO2 --> MACR + NO3                                                                       ', &
     '  MACROO + SO2 --> SO4 + MACR                                                                       ', &
     '        MACROO --> MRP                                                                              ', &
     '        MACROO --> H2O2 + MACR                                                                      ', &
     '    MVKOO + CO --> MVK                                                                              ', &
     '    MVKOO + NO --> MVK + NO2                                                                        ', &
     '   MVKOO + NO2 --> MVK + NO3                                                                        ', &
     '   MVKOO + SO2 --> SO4 + MVK                                                                        ', &
     '         MVKOO --> H2O2 + MVK                                                                       ', &
     '   MGLYOO + CO --> MGLY                                                                             ', &
     '   MGLYOO + NO --> MGLY + NO2                                                                       ', &
     '  MGLYOO + NO2 --> MGLY + NO3                                                                       ', &
     '  MGLYOO + SO2 --> SO4 + MGLY                                                                       ', &
     '        MGLYOO --> H2O2 + MGLY                                                                      ', &
     '    MGLOO + CO --> MGLY                                                                             ', &
     '    MGLOO + NO --> MGLY + NO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '   MGLOO + NO2 --> MGLY + NO3                                                                       ', &
     '   MGLOO + SO2 --> SO4 + MGLY                                                                       ', &
     '         MGLOO --> MCO3 + MO2                                                                       ', &
     '         MGLOO --> H2O2 + MGLY                                                                      ', &
     '  CH3CHOO + CO --> ALD2                                                                             ', &
     '  CH3CHOO + NO --> ALD2 + NO2                                                                       ', &
     ' CH3CHOO + NO2 --> ALD2 + NO3                                                                       ', &
     ' CH3CHOO + SO2 --> SO4 + ALD2                                                                       ', &
     '       CH3CHOO --> H2O2 + ALD2                                                                      ', &
     '       CH3CHOO --> ACTA                                                                             ', &
     '     GAOO + CO --> GLYC                                                                             ', &
     '     GAOO + NO --> GLYC + NO2                                                                       ', &
     '    GAOO + NO2 --> GLYC + NO3                                                                       ', &
     '    GAOO + SO2 --> SO4 + GLYC                                                                       ', &
     '          GAOO --> H2O2 + GLYC                                                                      ', &
     '          GAOO --> HAC                                                                              ', &
     '     BENZ + OH --> BRO2                                                                             ', &
     '     TOLU + OH --> TRO2                                                                             ', &
     '     XYLE + OH --> XRO2                                                                             ', &
     '          MONX --> 3 CH2O                                                                           ', &
     '    BRO2 + HO2 --> LBRO2H                                                                           ', &
     '     BRO2 + NO --> LBRO2N                                                                           ', &
     '    TRO2 + HO2 --> LTRO2H                                                                           ', &
     '     TRO2 + NO --> LTRO2N                                                                           ', &
     '    XRO2 + HO2 --> LXRO2H                                                                           ', &
     '     XRO2 + NO --> LXRO2N                                                                           ', &
     '      NAP + OH --> NRO2 + OH                                                                        ', &
     '    NRO2 + HO2 --> LNRO2H + HO2                                                                     ', &
     '     NRO2 + NO --> LNRO2N + NO                                                                      ', &
     '            O3 --> 2 OH                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '            O3 --> OH + HO2                                                                         ', &
     '           NO2 --> NO + O3                                                                          ', &
     '          H2O2 --> 2 OH                                                                             ', &
     '            MP --> CH2O + OH + HO2                                                                  ', &
     '          CH2O --> CO + 2 HO2                                                                       ', &
     '          CH2O --> CO + H2                                                                          ', &
     '          HNO3 --> OH + NO2                                                                         ', &
     '          HNO2 --> OH + NO                                                                          ', &
     '          HNO4 --> OH + NO3                                                                         ', &
     '          HNO4 --> NO2 + HO2                                                                        ', &
     '           NO3 --> O3 + NO2                                                                         ', &
     '           NO3 --> NO + O2                                                                          ', &
     '          N2O5 --> NO2 + NO3                                                                        ', &
     '          ALD2 --> 0.12 MCO3 + 0.88 MO2 + 0.88 CO + HO2                                             ', &
     '          ALD2 --> CO + CH4                                                                         ', &
     '           PAN --> 0.7 MCO3 + 0.3 MO2 + 0.7 NO2 + 0.3 NO3                                           ', &
     '          RCHO --> ETO2 + CO + HO2                                                                  ', &
     '          ACET --> MCO3 + MO2                                                                       ', &
     '          ACET --> 2 MO2 + CO                                                                       ', &
     '           MEK --> 0.85 ETO2 + 0.15 RCO3 + 0.85 MCO3 + 0.15 MO2                                     ', &
     '          GLYC --> 0.9 CH2O + 0.07 OH + CO + 1.73 HO2 + 0.1 MOH                                     ', &
     '          GLYX --> 2 CO + 2 HO2                                                                     ', &
     '          GLYX --> 2 CO + H2                                                                        ', &
     '          GLYX --> CH2O + CO                                                                        ', &
     '          MGLY --> MCO3 + CO + HO2                                                                  ', &
     '           MVK --> PRPE + CO                                                                        ', &
     '           MVK --> CH2O + MCO3 + CO + HO2                                                           ', &
     '           MVK --> RCO3 + MO2                                                                       ', &
     '          MACR --> 0.33 IMAO3 + 0.33 MAOP + 0.33 MRO2 + 0.67 CH2O + 0.67 MCO3 ... etc.              ', &
     '          MACR --> MGLY + CH2O + MCO3 + CO + 2 HO2                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '           HAC --> CH2O + MCO3 + HO2                                                                ', &
     '          INPN --> RCHO + OH + NO2 + HO2                                                            ', &
     '          PRPN --> RCHO + OH + NO2 + HO2                                                            ', &
     '           ETP --> ALD2 + OH + HO2                                                                  ', &
     '          RA3P --> RCHO + OH + HO2                                                                  ', &
     '          RB3P --> ACET + OH + HO2                                                                  ', &
     '           R4P --> RCHO + OH + HO2                                                                  ', &
     '            PP --> CH2O + ALD2 + OH + HO2                                                           ', &
     '            RP --> ALD2 + OH + HO2                                                                  ', &
     '           RIP --> 0.005 LVOC + 0.275 HC5 + 0.71 CH2O + 0.285 MACR + 0.425 MVK ... etc.             ', &
     '           IAP --> 0.26 GLYC + 0.58 MGLY + 0.36 HAC + OH + 0.67 CO + HO2 ... etc.                   ', &
     '          ISNP --> RCHO + OH + NO2 + HO2                                                            ', &
     '           VRP --> 0.7 GLYC + 0.3 MGLY + 0.3 CH2O + 0.7 MCO3 + OH + 0.3 HO2 ... etc.                ', &
     '           MRP --> 0.5 CH2O + HAC + OH + 0.5 CO + HO2                                               ', &
     '          MAOP --> CH2O + MCO3 + OH                                                                 ', &
     '          R4N2 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 ... etc.               ', &
     '           MAP --> OH + MO2                                                                         ', &
     '         MACRN --> MGLY + 0.5 CH2O + HAC + NO2 + 0.5 CO + HO2                                       ', &
     '          MVKN --> GLYC + MCO3 + NO2                                                                ', &
     '        ISOPNB --> HC5 + NO2 + HO2                                                                  ', &
     '          IPMN --> 0.4 CO2 + 0.6 IMAO3 + 0.4 CH2O + 0.4 MCO3 + 0.6 NO2 ... etc.                     ', &
     '           Br2 --> 2 Br                                                                             ', &
     '           BrO --> O3 + Br                                                                          ', &
     '          HOBr --> OH + Br                                                                          ', &
     '         BrNO3 --> NO3 + Br                                                                         ', &
     '         BrNO3 --> BrO + NO2                                                                        ', &
     '         BrNO2 --> NO2 + Br                                                                         ', &
     '         CHBr3 --> 3 Br                                                                             ', &
     '           MPN --> CH2O + NO3 + HO2                                                                 ', &
     '           MPN --> MO2 + NO2                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(4) :: EQN_NAMES_17 = (/ &
     '        ISOPND --> HC5 + NO2 + HO2                                                                  ', &
     '        PROPNN --> CH2O + MO2 + NO2 + CO                                                            ', &
     '         ETHLN --> CH2O + NO2 + CO + HO2                                                            ', &
     '         ATOOH --> CH2O + MCO3 + OH                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(514) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17 /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
